"""auto

Revision ID: 01b0542a1672
Revises: ef54ab080136
Create Date: 2025-09-20 18:01:53.925993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b0542a1672'
down_revision: Union[str, Sequence[str], None] = 'ef54ab080136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_metadata',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ingested_columns', sa.JSON(), nullable=False),
    sa.Column('computed_columns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_metadata'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_metadata')
    # ### end Alembic commands ###
