"""auto

Revision ID: 19356b90bbb3
Revises: f29260e2b864
Create Date: 2025-09-16 23:17:18.368712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19356b90bbb3'
down_revision: Union[str, Sequence[str], None] = 'f29260e2b864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('computed_content', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('computed_content_hash', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('computed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'computed_at')
    op.drop_column('transactions', 'computed_content_hash')
    op.drop_column('transactions', 'computed_content')
    # ### end Alembic commands ###
