"""auto

Revision ID: a6eb0ee16424
Revises: 
Create Date: 2025-09-15 00:56:16.389621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6eb0ee16424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(file_path) >= 1', name=op.f('ck_statements_statement_filepath_nonempty')),
    sa.CheckConstraint('length(filename) >= 1', name=op.f('ck_statements_statement_filename_nonempty')),
    sa.CheckConstraint('length(id) >= 1', name=op.f('ck_statements_statement_id_nonempty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statements'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    # ### end Alembic commands ###
