"""Add columns field to statements

Revision ID: ef54ab080136
Revises: 5efdf44bd508
Create Date: 2025-09-16 23:42:20.431998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef54ab080136'
down_revision: Union[str, Sequence[str], None] = '5efdf44bd508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('columns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'columns')
    # ### end Alembic commands ###
