"""auto

Revision ID: f26421efdbdf
Revises: 2ce862bd6837
Create Date: 2025-09-16 21:24:21.407570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26421efdbdf'
down_revision: Union[str, Sequence[str], None] = '2ce862bd6837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('statement_id', sa.String(length=64), nullable=False),
    sa.Column('ingested_content', sa.JSON(), nullable=False),
    sa.Column('ingested_content_hash', sa.String(length=64), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(id) >= 1', name=op.f('ck_transactions_transaction_id_nonempty')),
    sa.CheckConstraint('length(statement_id) >= 1', name=op.f('ck_transactions_transaction_statement_id_nonempty')),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_transactions_statement_id_statements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
