"""Add unique constraint on transaction content hash

Revision ID: f29260e2b864
Revises: a5ff795b8fdf
Create Date: 2025-09-16 21:37:04.425346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29260e2b864'
down_revision: Union[str, Sequence[str], None] = 'a5ff795b8fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transaction_statement_content', ['statement_id', 'ingested_content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transaction_statement_content', type_='unique')
    # ### end Alembic commands ###
